# .github/workflows/hello-world.yml
#The name of the workflow, will be displayed on the Github actions page
name: Continuous Deployment
# when to execute it, similar to Azure DevOps trigger keyword
on: push

# list of jobs to execute
jobs:
  hello-job:
    name: Greeting
    # which OS to use when running this action
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env: # Set the secret as an environmental variable
        super_secret: ${{ secrets.Identity }}
      run: |
        echo Hello World! I am a $super_secret
  print-secret:
    name: Secret
    # which OS to use when running this action
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env: # Set the secret as an environmental variable
        super_secret: ${{ secrets.Identity }}
      run: |
        cat $HOME/secrets/my_secret.json